version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py initialize_rabbitmq &&
            python manage.py wait_for_db &&
            python manage.py migrate &&
            pip install debugpy -t /tmp &&
            python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading"
    env_file: env/app.env
    ports:
      - "8000:8000"
      - "5678:5678"
    restart: always
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
      - blastn_storage:/mnt/data/blastn_storage
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - olatcg-bridge

  db:
    image: postgres:13-alpine
    env_file: env/db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    restart: always
    networks:
      - olatcg-bridge

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
    networks:
      - olatcg-bridge

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - ./data/rabbitmq:/var/lib/rabbitmq/
    env_file: env/rabbitmq.env
    networks:
      - olatcg-bridge

volumes:
  postgres:
  blastn_storage:

networks:
  olatcg-bridge:
    name: olatcg-bridge
    driver: bridge