version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    env_file: ./env/app.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    env_file: ./env/db.env
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "6379:6379"
  