# Generated by Django 4.2.19 on 2025-06-12 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(choices=[('PAIRWISE_ALIGNMENT', 'Pairwise Alignment'), ('HOMOLOGY_SEARCH', 'Homology Search'), ('TAXONOMY_TREE', 'Taxonomy Tree')], max_length=18)),
                ('status', models.CharField(blank=True, choices=[('WAITING', 'Waiting'), ('STARTED', 'Started'), ('FAILED', 'Failled'), ('SUCCEEDED', 'Succeeded')], default='WAITING', max_length=9)),
                ('parameters', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(max_length=5000)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='core.analysis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(default=None, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('results', models.JSONField()),
                ('file', models.CharField(max_length=1000, null=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='core.analysisinput')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.experiment'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='generated_from_analysis',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_analysis', to='core.analysis'),
        ),
    ]
