# Generated by Django 3.2.25 on 2024-07-17 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_analysis_generated_from_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alignments', to='core.analysis'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='generated_from_analysis',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_analysis', to='core.analysis'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analyses', to='core.tool'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxonomies', to='core.analysis'),
        ),
    ]
