# Generated by Django 3.2.25 on 2024-07-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alignmentanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignmentanalysis',
            name='id',
        ),
        migrations.AddField(
            model_name='alignmentanalysis',
            name='analysis',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.analysis'),
            preserve_default=False,
        ),
    ]
