# Generated by Django 3.2.25 on 2024-07-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240712_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignment',
            name='alignment_type',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('LOCAL', 'Local')], default='LOCAL', max_length=6),
        ),
        migrations.AddField(
            model_name='biologicalsequence',
            name='alignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='biological_sequences', to='core.alignment'),
        ),
        migrations.AddField(
            model_name='biologicalsequence',
            name='bases',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='biologicalsequence',
            name='country_origin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biologicalsequence',
            name='external_database_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biologicalsequence',
            name='type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('PROTEIN', 'PROTEIN')], default='DNA', max_length=7),
        ),
        migrations.AddField(
            model_name='homologyanalysis',
            name='coefficiente_of_variation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='description',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='taxonomy_analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxonomies', to='core.homologyanalysis'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alignmentanalysis',
            name='identity_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alignmentanalysis',
            name='query_external_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alignmentanalysis',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alignmentanalysis',
            name='similarity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alignmentanalysis',
            name='target_external_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='homologyanalysis',
            name='newick',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
