# Generated by Django 3.2.25 on 2024-07-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240712_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='taxonomy_analysis',
        ),
        migrations.AddField(
            model_name='alignment',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alignments', to='core.analysis'),
        ),
        migrations.AddField(
            model_name='alignment',
            name='taxonomy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alignments', to='core.taxonomy'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxonomies', to='core.analysis'),
        ),
    ]
