# Generated by Django 3.2.25 on 2024-07-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240717_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biologicalsequence',
            old_name='country_origin',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='biologicalsequence',
            old_name='external_database_id',
            new_name='query_sequence_id',
        ),
    ]
