# Generated by Django 3.2.25 on 2024-07-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240731_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalsequence',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
