# Generated by Django 3.2.25 on 2024-07-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240712_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alignment',
            old_name='alignment_type',
            new_name='type',
        ),
    ]
