# Generated by Django 3.2.25 on 2024-07-31 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blastninput_blastnoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastninput',
            name='input_file',
            field=models.FileField(blank=True, upload_to='blast/inputs/'),
        ),
        migrations.AddField(
            model_name='blastnoutput',
            name='input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outputs', to='core.blastninput'),
        ),
        migrations.AlterField(
            model_name='blastnoutput',
            name='output_file',
            field=models.FileField(upload_to='blast/outputs/'),
        ),
    ]
