# Generated by Django 3.2.25 on 2024-07-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240731_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blastninput',
            name='input_file',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='blastnoutput',
            name='output_file',
            field=models.BinaryField(),
        ),
    ]
