# Generated by Django 3.2.25 on 2024-08-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240804_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxonomy',
            old_name='tax_external_id',
            new_name='external_tax_id',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='family',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='order',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='phylum',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='species',
        ),
    ]
