# Generated by Django 3.2.25 on 2024-08-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240805_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biologicalsequence',
            old_name='description',
            new_name='external_sequence_id',
        ),
        migrations.RenameField(
            model_name='taxonomy',
            old_name='description',
            new_name='lineage',
        ),
        migrations.RenameField(
            model_name='taxonomy',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='biologicalsequence',
            name='query_sequence_id',
        ),
        migrations.RemoveField(
            model_name='biologicalsequence',
            name='title',
        ),
    ]
