# Generated by Django 3.2.25 on 2024-08-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240805_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastTreeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file_path', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file_path', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='tool',
        ),
        migrations.AddField(
            model_name='analysis',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, related_name='analyses', to='core.Tool'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='type',
            field=models.CharField(choices=[('ALIGNMENT', 'Alignment'), ('HOMOLOGY', 'Homology'), ('TAXONOMY_TREE', 'Taxonomy Tree')], default='ALIGNMENT', max_length=13),
        ),
        migrations.CreateModel(
            name='MuscleOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muscle_outputs', to='core.analysis')),
                ('input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outputs', to='core.muscleinput')),
            ],
        ),
        migrations.AddField(
            model_name='muscleinput',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muscle_inputs', to='core.analysis'),
        ),
        migrations.CreateModel(
            name='FastTreeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file', models.TextField(blank=True, null=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fasttree_outputs', to='core.analysis')),
                ('input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outputs', to='core.fasttreeinput')),
            ],
        ),
        migrations.AddField(
            model_name='fasttreeinput',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fasttree_inputs', to='core.analysis'),
        ),
    ]
