# Generated by Django 3.2.25 on 2024-08-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240809_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasttreeinput',
            name='input_file_path',
        ),
        migrations.RemoveField(
            model_name='muscleinput',
            name='input_file_path',
        ),
        migrations.RemoveField(
            model_name='muscleoutput',
            name='output_file_path',
        ),
        migrations.AddField(
            model_name='fasttreeinput',
            name='input_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muscleinput',
            name='input_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muscleoutput',
            name='output_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='core.Tool'),
        ),
        migrations.AlterField(
            model_name='fasttreeoutput',
            name='output_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
