# Generated by Django 3.2.25 on 2024-10-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240809_0800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(blank=True, choices=[('WAITING_FOR_EXECUTION', 'Waiting for execution'), ('IN_EXECUTION', 'In Execution'), ('EXECUTION_FAILED', 'Execution Failled'), ('EXECUTION_SUCCEEDED', 'Execution Succeeded')], default='WAITING_FOR_EXECUTION', max_length=21),
        ),
        migrations.AlterField(
            model_name='biologicalsequence',
            name='type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('GAPPED_DNA', 'Gapped DNA'), ('RNA', 'RNA'), ('GAPPED_RNA', 'Gapped RNA'), ('PROTEIN', 'Protein'), ('GAPPED_PROTEIN', 'Gapped Protein')], default='DNA', max_length=14),
        ),
        migrations.AlterField(
            model_name='biopythonbioalignpairwisealignerinput',
            name='analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='biopython_input', to='core.analysis'),
        ),
    ]
