# Generated by Django 3.2.25 on 2024-10-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20241010_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasttreeoutput',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='muscleoutput',
            name='analysis',
        ),
    ]
