# Generated by Django 3.2.25 on 2024-10-17 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20241014_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalsequence',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='biopythonbioalignpairwisealignerinput',
            name='analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='biopython_bio_align_pairwise_aligner_input', to='core.analysis'),
        ),
    ]
